/*
 * generated by Xtext
 */
package iit.dsl.transspecs.scoping;

import iit.dsl.coord.scoping.CoordTransDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class TransSpecsScopeProvider extends CoordTransDslScopeProvider {

}
