/*
 * generated by Xtext
 */
package iit.dsl.transspecs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TransSpecsRuntimeModule extends iit.dsl.transspecs.AbstractTransSpecsRuntimeModule {

}
