/*
 * generated by Xtext 2.10.0
 */
package iit.dsl.transspecs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TransSpecsStandaloneSetup extends TransSpecsStandaloneSetupGenerated {

	def static void doSetup() {
		new TransSpecsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
